const interests = [
	'Air sports',
	'Archery',
	'Astronomy',
	'BASE jumping',
	'Baseball',
	'Basketball',
	'Beekeeping',
	'Bird watching',
	'Blacksmithing',
	'Board sports',
	'Bodybuilding',
	'Brazilian jiu-jitsu',
	'Camping',
	'Canyoning',
	'Dowsing',
	'Driving',
	'Fishing',
	'Flag football',
	'Flying',
	'Flying disc',
	'Foraging',
	'Freestyle football',
	'Gardening',
	'Geocaching',
	'Ghost hunting',
	'Graffiti',
	'Handball',
	'High-power rocketry',
	'Hiking',
	'Hooping',
	'Horseback riding',
	'Hunting',
	'Inline skating',
	'Jogging',
	'Kayaking',
	'Kite flying',
	'Kitesurfing',
	'LARPing',
	'Letterboxing',
	'Longboarding',
	'Martial arts',
	'Metal detecting',
	'Motor sports',
	'Mountain biking',
	'Mountaineering',
	'Mushroom hunting/mycology',
	'Netball',
	'Nordic skating',
	'Orienteering',
	'Paintball',
	'Parkour',
	'Photography',
	'Polo',
	'Powerlifting',
	'Rafting',
	'Rappelling',
	'Road biking',
	'Rock climbing',
	'Roller skating',
	'Rugby',
	'Running',
	'Sailing',
	'Sand art',
	'Scouting',
	'Scuba diving',
	'Sculling or rowing',
	'Shooting',
	'Shopping',
	'Skateboarding',
	'Skiing',
	'Skimboarding',
	'Skydiving',
	'Slacklining',
	'Snowboarding',
	'Stone skipping',
	'Sun bathing',
	'Surfing',
	'Swimming',
	'Taekwondo',
	'Tai chi',
	'Topiary',
	'Travel',
	'Urban exploration',
	'Vacation',
	'Vehicle restoration',
	'Walking',
	'Water sports'
];

export default interests;
